---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devito-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devito-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: devito-server
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: devito-server
          image: devitoaks.azurecr.io/daks-base:v8
          command: ['/venv/bin/dask-scheduler']
          ports:
            - containerPort: 8786
              name: devito-server
            - containerPort: 8787
              name: daskdashboard
---

apiVersion: v1
kind: Service
metadata:
  name: devito-server
spec:
  type: LoadBalancer
  ports:
    - name: aaa
      port: 8786
      targetPort: 8786
    - name: bbb
      port: 8787
      targetPort: 8787
  selector:
    app: devito-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devito-worker
spec:
  replicas: 15
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: devito-worker
  template:
    metadata:
      labels:
        app: devito-worker
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: devito-worker
          env:
            - name: PYTHONPATH
              value: /app
            - name: DEVITO_LANGUAGE
              value: "openmp"
            - name: DEVITO_LOGGING
              value: "DEBUG"
            - name: OMP_PROC_BIND
              value: "TRUE"
            - name: "OMP_PLACES"
              value: "cores"
            - name: "OMP_NUM_THREADS"
              value: "4"
          image: devitoaks.azurecr.io/daks-base:v8
          command: ['/venv/bin/dask-worker', 'tcp://devito-server:8786', '--memory-limit', '13G', '--resources', 'tasks=1', '--nprocs', '1', '--nthreads', '1']
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 14G
              cpu: 4
            limits:
              memory: 14G
              cpu: 4
