name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DASK_SERVER_IP: ${{ secrets.DASK_SERVER_IP }}
  BLOB_ACCOUNT_NAME: ${{ secrets.BLOB_ACCOUNT_NAME }}
  BLOB_ACCOUNT_KEY: ${{ secrets.BLOB_ACCOUNT_KEY }}
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -f kubernetes/Dockerfile -t navjotk/daks_test:latest .
    - name: Push to docker hub
      run: |
        docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        docker push navjotk/daks_test:latest
        
    - name: Test with pytest
      run: docker run  -e DASK_SERVER_IP=$DASK_SERVER_IP -e BLOB_ACCOUNT_NAME=$BLOB_ACCOUNT_NAME -e BLOB_ACCOUNT_KEY=$BLOB_ACCOUNT_KEY navjotk/daks_test:latest py.test -svx tests/
    
    - name: Run scripts
      run: docker run  -e DASK_SERVER_IP=$DASK_SERVER_IP -e BLOB_ACCOUNT_NAME=$BLOB_ACCOUNT_NAME -e BLOB_ACCOUNT_KEY=$BLOB_ACCOUNT_KEY navjotk/daks_test:latest make fwi
